steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/chat-bot/dummy_api', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/chat-bot/dummy_api']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run',
    'deploy', 'dummy_api',
    '--image', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/chat-bot/dummy_api',
    '--region', 'us-central1']
images:
- 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/chat-bot/dummy_api'